### ISSUE TITLE
Undefined property missing or not caught

### ISSUE THREAD

**Issue by RasPhilCo** [heroku/heroku-cli-util#101]
Need to explore more, but:

```
$ heroku local:run bin/rails -v
[OKAY] Loaded ENV .env File as KEY=VALUE Format
Could not find i18n-0.7.0 in any of the sources
Run `bundle install` to install missing gems.
TypeError: Cannot read property 'body' of undefined
    at getErrorMessage (/Users/user/src/github.com/heroku/heroku-local/node_modules/heroku-cli-util/lib/errors.js:33:10)
    at error (/Users/user/src/github.com/heroku/heroku-local/node_modules/heroku-cli-util/lib/errors.js:53:30)
    at handleErr (/Users/user/src/github.com/heroku/heroku-local/node_modules/heroku-cli-util/lib/errors.js:100:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by dickeyxxx** [comment]
this isn't a v6-specific thing is it?
