### ISSUE TITLE
Cannot assign to read only property 'has256'

### ISSUE THREAD

**Issue by brissenden** [heroku/heroku-cli-util#58]
Since this morning i'm getting this error:

```
2016/04/08 09:38:28 truncating error log...
2016/04/08 09:38:28 cleaning up tmp dirs...
2016/04/08 09:38:28 heroku-cli: Installing core plugins...
2016/04/08 09:38:28 open /var/lib/buildkite-agent/.heroku/config.json: no such file or directory
2016/04/08 09:39:02  done
2016/04/08 09:39:02 open /var/lib/buildkite-agent/.heroku/config.json: no such file or directory
2016/04/08 09:39:02 open /var/lib/buildkite-agent/.heroku/config.json: no such file or directory
2016/04/08 09:39:04 TypeError: Cannot assign to read only property 'has256' of false
    at findBestHerokuColor (/var/lib/buildkite-agent/.heroku/node_modules/heroku-run/node_modules/heroku-cli-util/lib/spinner.js:9:19)
    at new Spinner (/var/lib/buildkite-agent/.heroku/node_modules/heroku-run/node_modules/heroku-cli-util/lib/spinner.js:28:23)
    at Run.updateStatus (/var/lib/buildkite-agent/.heroku/node_modules/heroku-run/commands/run.js:41:22)
    at Run.<anonymous> (/var/lib/buildkite-agent/.heroku/node_modules/heroku-run/commands/run.js:21:12)
    at next (native)
    at onFulfilled (/var/lib/buildkite-agent/.heroku/node_modules/co/index.js:65:19)
    at _fulfilled (/var/lib/buildkite-agent/.heroku/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/lib/buildkite-agent/.heroku/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/lib/buildkite-agent/.heroku/node_modules/q/q.js:796:13)
    at /var/lib/buildkite-agent/.heroku/node_modules/q/q.js:604:44
```

This may be connected to your latest changed @dickeyxxx . Do you have any idea what went wrong?

**Comment by ransombriggs** [comment]
@brissenden I believe that @dickeyxxx shipped a fix for this today, if you could please run `heroku update` and please try again?

**Comment by brissenden** [comment]
@ransombriggs You are right, it's fixed by @dickeyxxx :+1:
