### ISSUE TITLE
Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by xavdid** [heroku/heroku-cli-util#69]
Hey guys! The when I require the module, I'm getting what looks like a syntax error? 

```bash
% node
> let cli = require('heroku-cli-util')
/Users/david/projects/heroku-config/node_modules/heroku-cli-util/lib/action.js:16
  if (options.then) [options, promise] = [{}, options]
                    ^^^^^^^^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/david/projects/heroku-config/node_modules/heroku-cli-util/index.js:11:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

__Versions__
Node: `5.7.1`
heroku-cli-util: `6.0.13`

For now I'll just downgrade, but I thought it's something you might be interested in. Thanks!

__Edit__: The last version without this error is `6.0.3`.

**Comment by dickeyxxx** [comment]
you need to update your node version

**Comment by xavdid** [comment]
Fair enough. I couldn't find version requirements anywhere. Might be worth
adding `engines` to package.json if that's a hard requirement.

~DavidB
[davidbrownman.com]
c: 303.819.0850

**Comment by dickeyxxx** [comment]
sure, I can do that
